### ISSUE TITLE
Operadores da classe matriz não fazem o que se esperaria

### ISSUE THREAD

**Issue by oangelo** [joaovitor32/Algoritimos-JVML#5]
https://github.com/joaovitor32/Algoritimos-JVML/blob/936ef68c9d7826d5c93829b97a359f8c181ef0b5/Trabalhos/3%C2%B0%20Bateria%20de%20trabalhos/Tests.h#L1

Os operadores +, - , * devem implementar as operações algébricas típicas entre matrizes, não só sobre um elemento da matriz.

**Comment by joaovitor32** [comment]
Mas é o código que está errado ou os testes que estão mal implementados?

**Comment by joaovitor32** [comment]
Aparentemente, os Testes e os Códigos estão funcionando plenamente agora.
